### ISSUE TITLE
Unable to pull historical results of team_rosters via leagueHistory = TRUE

### ISSUE THREAD

**Issue by KevinLeone** [k5cents/fflr#48]
Only latest scoringPeriodID by season is provided via leagueHistory = TRUE in most cases. Specifically looking for a way to utilize these functions to loop through the API for each Season Period ID /scoringPeriod ID, but unable to select parameters/add helper functions to environment which aren't defined. 

Desired outcome example:
scoring_history <- combine_history(team_roster, **param such as: scoringPeriodId = ALL**), provide lists of players for scoringPeriodIds 1-16, 1-17, 1-18, etc.

**Comment by kiernann** [comment]
Unfortunately, I think this is a limitation of the ESPN API.

The way to do what you're looking for is to _not_ use `leagueHistory = TRUE` and instead do a separate call to `team_roster()` with `seasonId` and `scoringPeriodId` set separately for each year/week. A tricky thing is you _can_ pass `seasonId` to these functions because of the `...` argument.

Like a loop within a loop would work.

```r
for (year in 2020:2023) {
  for (week in 1:15) {
    team_roster(
      seasonId = year,
      scoringPeriodId = week
    )
  }
}
```

In my limited testing that does seem to return the right roster for weeks in the middle of the season. Beware that maaaaybe some older seasons don't have this data saved. I've found that some things in the API are different for seasons before like 2018.

Let me know if that works?
